### ISSUE TITLE
Display version number in webinterface

### ISSUE THREAD

**Issue by linupi** [schreiber-lab/scicat-schema-extension#14]
use the version defined in package.json to display it in the side menu

https://github.com/schreiber-lab/scicat-schema-extension/blob/485e2685a64c43711b97f9a0f72209304e62d67f/frontend/package.json#L3

**Comment by AnastasiiaDeveloper** [comment]
Did it!

**Comment by AnastasiiaDeveloper** [comment]
In the brunch 21-crud-for-schema-keys

**Comment by AlexanderHinderhofer** [comment]
Task implemented
